apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-key-vault
spec:
  provider: azure
  secretObjects:
  - secretName: pfx
    type: Opaque
    data:
    - objectName: tls.pfx
      key: value
  - secretName: tls
    type: kubernetes.io/tls
    data: 
    - objectName: pem
      key: tls.key
    - objectName: pem
      key: tls.crt
  parameters:
    clientID: {{ .Values.clientId }}
    keyvaultName: {{ .Values.keyVaultName }}
    tenantId: {{ .Values.keyVaultTenant }}
    objects:  |
      array:
        - |
          objectName: {{ .Values.certificateName }}
          objectAlias: tls.pfx
          objectFormat: pfx
          objectEncoding: base64
          objectType: secret
        - |
          objectName: {{ .Values.certificateName }}
          objectAlias: pem
          objectType: secret
          